### ISSUE TITLE
코어 파괴 오류

### ISSUE THREAD

**Issue by sonogram70** [monun/minigame-fortress#3]
제가 이 포트리스 게임을 플레이하는데 다른 건 잘 작동했는데 다른 사람 코어가 부숴졌을 때 코어가 부숴졌다는 메시지가 안 떠요.

**Comment by sonogram70** [comment]
플러그인은 delayed-respawn, team-spawn, minigame-fortress, protocollib, block-trigger을 적용했습니다

**Comment by Iseome** [comment]
> 플러그인은 delayed-respawn, team-spawn, minigame-fortress, protocollib, block-trigger을 적용했습니다

믈럭 트리거 사용법 아시나요? 특정 블럭을 어떻게 해야하는지 모르겠습니다

**Comment by sonogram70** [comment]
그건 저도 잘 모르겠네요

**Comment by sonogram70** [comment]
아마 그거 때문에 저도 오류가 뜬 것 같습니다
