### ISSUE TITLE
About the JDK

### ISSUE THREAD

**Issue by qogusdn1017** [monun/minigame-fortress#7]
딱히 올릴곳이 없기에 여기에라도 올려봅니다만...

#6 과 같이 JDK 11이 설치되어있지 않아서 서버동작시 오류가 발생되는 경우가 monun (noonmaru)님 레포지토리 이슈에서 많이 발견되었습니다.

Documentation을 걸거나 (시간이 없는 경우 플리퀘 해드릴 수 있습니다) PowerShell 스크립트에 JDK 11을 확인하고 자동 설치할 수 있는 명령들을 추가해보는건 어떨지 조심스레 여쭈어봅니다.

**Comment by monun** [comment]
된다면 좋겠지만 기존 jdk를 사용하시는 분들의 환경변수는 망칠수 없기에..
Grep으로 경고정도는 띄우면 좋을듯합니다

**Comment by qogusdn1017** [comment]
앗 알겠습니다! 질문 하나만 남기고 이슈 닫겠습니다.

noonmaru 계정의 parkour maker는 혹시 종결인가요...? 이사를 오지 않고 build.gradle.kts도 업데이트되지 않아 ProtocolLib 디펜던시 받는 과정에서 오류나가지고 이슈가 달렸거든요...

바쁘실텐데 답해주셔서 감사합니다! 해피코딩!

**Comment by monun** [comment]
나중에 컨텐츠 할때 업데이트 하겠쥬 ㅋㅋㅋ

**Comment by qogusdn1017** [comment]
> 나중에 컨텐츠 할때 업데이트 하겠쥬 ㅋㅋㅋ

앜ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
